//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsriber
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subsriber()
        {
            this.ConectedService = new HashSet<ConectedService>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronumic { get; set; }
        public int CodeGender { get; set; }
        public int IDPassport { get; set; }
        public string NumberContract { get; set; }
        public System.DateTime DateCreateContract { get; set; }
        public string AdressUser { get; set; }
        public string FactAdress { get; set; }
        public int District { get; set; }
        public int TypeContract { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConectedService> ConectedService { get; set; }
        public virtual ContractType ContractType { get; set; }
        public virtual District District1 { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual PassportInfo PassportInfo { get; set; }
    }
}
